### PR TITLE
Added component drive

### PR DESCRIPTION
**Pull request by Zabqer**
Drive component for HardDrive in Unmanaged mode

### CODE REVIEW

**Comment by gamax92** [comment]
Thanks for this, will review soon.

**Comment by zenith391** [comment]
it's been a whole year it isn't in OCEmu, it's getting me tired to manually add the file, is OCEmu not being maintened anymore?

**Comment by BlueAmulet** [comment]
Finally added this, though with a few changes and bug fixes:
directory is now filename, and is used to preload the drive with data
data is now saved at `address/data.bin` like the eeprom
tier 3 platter corrected to 8
offset check did not subtract 1
readSector did not add one for sub start
writeSector did not properly truncate the value written
readByte did not return values as a signed byte
writeByte did not write to the right location, or wrap values to 0-255

**Comment by gamax92** [comment]
Finally added this, though with a few changes and bug fixes:
directory is now filename, and is used to preload the drive with data
data is now saved at address/data.bin like the eeprom
tier 3 platter corrected to 8
offset check did not subtract 1
readSector did not add one for sub start
writeSector did not properly truncate the value written
readByte did not return values as a signed byte
writeByte did not write to the right location, or wrap values to 0-255

Also sorry to those watching the repository for the incorrect post

**Pull request closed without merging**
